import Head from "next/head";
import { useState } from "react";


export default function Home() {
  const [input, setInput] =useState<string>('')

  return (
    <>
      <Head>
        <title>AI Marketing Copy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-7xl mx-auto">
        <h2 className="text-2xl font-bold text-center p-12 ">
          Marketing Copy Generator
        </h2>
        {/* input field  */}
        <div className="flex flex-col gap-4  justify-center w-1/3 mx-auto">
          <div className="relative w-full">
            <textarea
              // type="text"
              rows={3}
              value={input}
              onChange={e=>setInput(e.target.value)}
              className="border-2 border-gray-300 w-full bg-white  p-4 rounded-lg text-sm focus:outline-none resize-none"
              placeholder="Enter your text here"
            />
            {/* Charactor limit */}
            <div className="absolute bottom-2 right-2 text-gray-400 text-xs">
              <span>{input.length}</span>/30
            </div>
          </div>
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Generate
          </button>
        </div>
      </div>
    </>
  );
}
